# Generated by Django 3.0.7 on 2020-12-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.s3
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('image', models.ImageField(blank=True, null=True, upload_to=helpers.s3.UploadFileTo('posts-images', 'post'))),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='topics.Topic', to_field='url_name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
