# Generated by Django 3.0.7 on 2020-12-16 00:33

from django.db import migrations, models
import helpers.s3


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.s3.UploadFileTo('comments-images', 'comment')),
        ),
    ]
